### ISSUE TITLE
my steam library directory is like this 

### ISSUE THREAD

**Issue by mountaincastle47** [pukmajster/funky#14]
C:\SteamLibrary\steamapps
so i can't add this directory in setup :(

**Comment by mountaincastle47** [comment]
also it seems like steam and Steam is different too so i can't add another directory (seperate issue)

**Comment by pukmajster** [comment]
what do you mean by "steam" and "Steam"?

**Comment by mountaincastle47** [comment]
> what do you mean by "steam" and "Steam"?

i mean the program require the s to be a capital s while my directory isn't

**Comment by pukmajster** [comment]
Can you try the latest [v0.2.2](https://github.com/pukmajster/funky/releases/tag/v0.2.2) update? I got rid of the check altogether.

**Comment by pukmajster** [comment]
Other users have said that this has been indeed fixed.
