### ISSUE TITLE
Doesn't seem to read "SteamLibrary" folders as valid

### ISSUE THREAD

**Issue by ChimiChamo** [pukmajster/funky#6]
Trying to setup the games directory, the direct steam folder works fine but the SteamLibrary folders where games can also be installed doesnt seem to be recognised

**Comment by pukmajster** [comment]
I take it you have l4d2 installed on another drive? I completely overlooked this possibility, in all honesty. I'll take a look.

**Comment by pukmajster** [comment]
fixed in 4033f0981cc2896546be060018d65af725227037, i'll ship it in 0.2.1 soonish
